# file: postgresql/tasks/extensions/postgis.yml

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed
  apt:
    name: "{{postgresql_ext_postgis_deps}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  notify:
    - restart postgresql
